Traceback (most recent call last):
  File "/home/aidan/Code/Work/berkeley/transformer-control/ebonye_transformer_control/trainSequential_ebonye_cartpole.py", line 665, in <module>
    main(args)
    ~~~~^^^^^^
  File "/home/aidan/Code/Work/berkeley/transformer-control/ebonye_transformer_control/trainSequential_ebonye_cartpole.py", line 591, in main
    model = model.to('cuda:0')
  File "/home/aidan/pyenvs/berk/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1355, in to
    return self._apply(convert)
           ~~~~~~~~~~~^^^^^^^^^
  File "/home/aidan/pyenvs/berk/lib/python3.13/site-packages/torch/nn/modules/module.py", line 915, in _apply
    module._apply(fn)
    ~~~~~~~~~~~~~^^^^
  File "/home/aidan/pyenvs/berk/lib/python3.13/site-packages/torch/nn/modules/module.py", line 915, in _apply
    module._apply(fn)
    ~~~~~~~~~~~~~^^^^
  File "/home/aidan/pyenvs/berk/lib/python3.13/site-packages/torch/nn/modules/module.py", line 942, in _apply
    param_applied = fn(param)
  File "/home/aidan/pyenvs/berk/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1341, in convert
    return t.to(
           ~~~~^
        device,
        ^^^^^^^
        dtype if t.is_floating_point() or t.is_complex() else None,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        non_blocking,
        ^^^^^^^^^^^^^
    )
    ^
  File "/home/aidan/pyenvs/berk/lib/python3.13/site-packages/torch/cuda/__init__.py", line 372, in _lazy_init
    torch._C._cuda_init()
    ~~~~~~~~~~~~~~~~~~~^^
RuntimeError: No CUDA GPUs are available
